; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "PLink"
!define UPDATE_VERSION "1.0.0.0"
!define PRODUCT_VERSION "1.0.0.0"
!define PRODUCT_WEB_SITE "http://github.com/"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\PLink.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define CONFIG_REG_FIDDLER_ROOT "HKLM"
!define CONFIG_REG_FIDDLER_KEY "SOFTWARE\Microsoft\Fiddler2"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define INSTALL_ROOT "version\${UPDATE_VERSION}"
!define CHROME_ROOT "ChromeExtension"

; MUI 1.67 compatible ------
!include "MUI2.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "PLink.ico"
!define MUI_UNICON "PLink.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

!define MUI_PAGE_CUSTOMFUNCTION_PRE checkpreinstall

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!define MUI_LICENSEPAGE_RADIOBUTTONS
!insertmacro MUI_PAGE_LICENSE "PLinkLicense.txt"
; Components page
!insertmacro MUI_PAGE_COMPONENTS
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\PLink.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Korean"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "setup\${UPDATE_VERSION}\PLinkSetup.exe"
InstallDir "$PROGRAMFILES\PLink"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show
RequestExecutionLevel admin

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Function checkpreinstall

	ReadRegStr $0 ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName"
	StrCmp $0 "" preinstallFalse preinstallTrue
	preinstallFalse:
		goto end
	preinstallTrue:
		MessageBox MB_YESNO "${PRODUCT_NAME} 클라이언트가 이미 설치되어 있습니다. 기존 버전의 클라이언트를 삭제하고 새 버전을 설치합니다." IDYES true IDNO false
		false:
			MessageBox MB_OK "이전 버전의 클라이언트를 제거하지 않으면 새 버전을 설치할 수 없습니다."
			Quit
		true:	
			StrCpy $R3 "$INSTDIR"
			ReadRegStr $R1 ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString"
		
			ExecWait '"$R1" /S'
			MessageBox MB_YESNO "이전 버전의 클라이언트가 제거되었습니다. 새 버전 인스톨을 계속하시겠습니까?" IDYES deletetemp IDNO stop
				stop:
					Quit
				deletetemp:
					DetailPrint "삭제가 완료되었습니다. : $R2"
					StrCpy "$INSTDIR" $R3
	end:
Functionend

Section "PLink" SEC01

  ; PLink 
  SetOutPath "$INSTDIR"
  File "${INSTALL_ROOT}\FiddlerCore.dll"
  File "${INSTALL_ROOT}\PLink.exe"
  File "${INSTALL_ROOT}\PLinkCore.dll"
  File "PLinkLicense.txt"
  File "README.md"
  
  ; PLink settings
  CreateDirectory "$SMPROGRAMS\PLink"
  CreateShortCut "$SMPROGRAMS\PLink\PLink.lnk" "$INSTDIR\PLink.exe"
  CreateShortCut "$DESKTOP\PLink.lnk" "$INSTDIR\PLink.exe"
  CreateShortCut "$QUICKLAUNCH\PLink.lnk" "$INSTDIR\PLink.exe"

  ; Fiddler Addon
  SetOutPath "$INSTDIR\AddOn"
  File "${INSTALL_ROOT}\AddOn\PLinkAddOn.dll"
  File "${INSTALL_ROOT}\AddOn\PLinkCore.dll"  
  
  ; Chrome Addon
  SetOutPath "$INSTDIR\${CHROME_ROOT}"
  File "${CHROME_ROOT}\logo.ico"
  File "${CHROME_ROOT}\manifest.json"
  File "${CHROME_ROOT}\popup.html"
  
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\PLink\Remove PLink.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\PLink.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\PLink.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UpdateVersion" "${UPDATE_VERSION}"  
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
SectionEnd

; Section descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC01} "PLink v${PRODUCT_VERSION}"
!insertmacro MUI_FUNCTION_DESCRIPTION_END


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name)는(은) 완전히 제거되었습니다."
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "$(^Name)을(를) 제거하시겠습니까?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\PLinkLicense.txt"
  Delete "README.md"  
  Delete "$INSTDIR\PLinkCore.dll"
  Delete "$INSTDIR\PLink.exe"
  Delete "$INSTDIR\FiddlerCore.dll"
  Delete "$INSTDIR\AddOn\PLinkCore.dll"
  Delete "$INSTDIR\AddOn\PLinkAddOn.dll"
  
  Delete "$INSTDIR\${CHROME_ROOT}\logo.ico"
  Delete "$INSTDIR\${CHROME_ROOT}\manifest.json"
  Delete "$INSTDIR\${CHROME_ROOT}\popup.html" 
  
  Delete "$SMPROGRAMS\PLink\Remove PLink.lnk"
  Delete "$DESKTOP\PLink.lnk"
  Delete "$SMPROGRAMS\PLink\PLink.lnk"
  Delete "$QUICKLAUNCH\PLink\PLink.lnk"

  RMDir "$SMPROGRAMS\PLink"
  RMDir /r "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd